"""Automatically generated file.

To update, run python3 scripts/gen_signal_metadata.py

Describes every signal in Tesla's telemetry catalog: its Field enum id, the
category and type Tesla documents, its unit and device/state class, and the
firmware floor below which a vehicle will never report it.

`value_type` is a hint. The entity type is decided from the Value oneof arm
the vehicle actually sends; this is what Tesla's documentation claims, which
is useful for the options UI and for validating units.

`enum_name` names the proto enum but not its members: those are read from the
live protobuf descriptor, so a proto bump cannot put them out of step with the
bindings actually decoding the stream.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class SignalMeta:
    """Everything known about one telemetry signal."""

    field_id: int
    category: str | None
    value_type: str | None
    enum_name: str | None
    unit: str | None
    device_class: str | None
    state_class: str | None
    min_firmware: str | None
    semi_only: bool
    documented: bool


SIGNALS: dict[str, SignalMeta] = {
    'DriveRail': SignalMeta(
        field_id=1,
        category='Driving',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ChargeState': SignalMeta(
        field_id=2,
        category='Charging',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'BmsFullchargecomplete': SignalMeta(
        field_id=3,
        category='Charging',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'VehicleSpeed': SignalMeta(
        field_id=4,
        category='Driving',
        value_type='real',
        enum_name=None,
        unit='mph',
        device_class='speed',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'Odometer': SignalMeta(
        field_id=5,
        category='Vehicle State',
        value_type='real',
        enum_name=None,
        unit='mi',
        device_class='distance',
        state_class='total_increasing',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'PackVoltage': SignalMeta(
        field_id=6,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='V',
        device_class='voltage',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'PackCurrent': SignalMeta(
        field_id=7,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='A',
        device_class='current',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'Soc': SignalMeta(
        field_id=8,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='%',
        device_class='battery',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DCDCEnable': SignalMeta(
        field_id=9,
        category='Charging',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'Gear': SignalMeta(
        field_id=10,
        category='Driving',
        value_type='enum',
        enum_name='ShiftState',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'IsolationResistance': SignalMeta(
        field_id=11,
        category='Service',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'PedalPosition': SignalMeta(
        field_id=12,
        category='Driving',
        value_type='real',
        enum_name=None,
        unit='%',
        device_class=None,
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'BrakePedal': SignalMeta(
        field_id=13,
        category='Driving',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiStateR': SignalMeta(
        field_id=14,
        category='Powertrain',
        value_type='enum',
        enum_name='DriveInverterState',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiHeatsinkTR': SignalMeta(
        field_id=15,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiAxleSpeedR': SignalMeta(
        field_id=16,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiTorquemotor': SignalMeta(
        field_id=17,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiStatorTempR': SignalMeta(
        field_id=18,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiVBatR': SignalMeta(
        field_id=19,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='V',
        device_class='voltage',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiMotorCurrentR': SignalMeta(
        field_id=20,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='A',
        device_class='current',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'Location': SignalMeta(
        field_id=21,
        category='Location',
        value_type='Location',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'GpsState': SignalMeta(
        field_id=22,
        category='Location',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'GpsHeading': SignalMeta(
        field_id=23,
        category='Location',
        value_type='real',
        enum_name=None,
        unit='°',
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'NumBrickVoltageMax': SignalMeta(
        field_id=24,
        category='Charging',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'BrickVoltageMax': SignalMeta(
        field_id=25,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='V',
        device_class='voltage',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'NumBrickVoltageMin': SignalMeta(
        field_id=26,
        category='Charging',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'BrickVoltageMin': SignalMeta(
        field_id=27,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='V',
        device_class='voltage',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'NumModuleTempMax': SignalMeta(
        field_id=28,
        category='Charging',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ModuleTempMax': SignalMeta(
        field_id=29,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class=None,
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'NumModuleTempMin': SignalMeta(
        field_id=30,
        category='Charging',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ModuleTempMin': SignalMeta(
        field_id=31,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class=None,
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'RatedRange': SignalMeta(
        field_id=32,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='mi',
        device_class='distance',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'Hvil': SignalMeta(
        field_id=33,
        category='Powertrain',
        value_type='enum',
        enum_name='HvilStatus',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DCChargingEnergyIn': SignalMeta(
        field_id=34,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='kWh',
        device_class='energy',
        state_class='total_increasing',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DCChargingPower': SignalMeta(
        field_id=35,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='kW',
        device_class='power',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ACChargingEnergyIn': SignalMeta(
        field_id=36,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='kWh',
        device_class='energy',
        state_class='total_increasing',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ACChargingPower': SignalMeta(
        field_id=37,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='kW',
        device_class='power',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ChargeLimitSoc': SignalMeta(
        field_id=38,
        category='Charging',
        value_type='integer',
        enum_name=None,
        unit='%',
        device_class='battery',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'FastChargerPresent': SignalMeta(
        field_id=39,
        category='Charging',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'EstBatteryRange': SignalMeta(
        field_id=40,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='mi',
        device_class='distance',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'IdealBatteryRange': SignalMeta(
        field_id=41,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='mi',
        device_class='distance',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'BatteryLevel': SignalMeta(
        field_id=42,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='%',
        device_class='battery',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'TimeToFullCharge': SignalMeta(
        field_id=43,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='h',
        device_class='duration',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ScheduledChargingStartTime': SignalMeta(
        field_id=44,
        category='Charging',
        value_type='timestamp',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ScheduledChargingPending': SignalMeta(
        field_id=45,
        category='Charging',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ScheduledDepartureTime': SignalMeta(
        field_id=46,
        category=None,
        value_type=None,
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=False,
    ),
    'PreconditioningEnabled': SignalMeta(
        field_id=47,
        category='Charging',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ScheduledChargingMode': SignalMeta(
        field_id=48,
        category='Charging',
        value_type='enum',
        enum_name='ScheduledChargingModeValue',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ChargeAmps': SignalMeta(
        field_id=49,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='A',
        device_class='current',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ChargeEnableRequest': SignalMeta(
        field_id=50,
        category='Charging',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ChargerPhases': SignalMeta(
        field_id=51,
        category='Charging',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ChargePortColdWeatherMode': SignalMeta(
        field_id=52,
        category='Charging',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ChargeCurrentRequest': SignalMeta(
        field_id=53,
        category='Charging',
        value_type='integer',
        enum_name=None,
        unit='A',
        device_class='current',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ChargeCurrentRequestMax': SignalMeta(
        field_id=54,
        category='Charging',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'BatteryHeaterOn': SignalMeta(
        field_id=55,
        category='Charging',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'NotEnoughPowerToHeat': SignalMeta(
        field_id=56,
        category='Charging',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'SuperchargerSessionTripPlanner': SignalMeta(
        field_id=57,
        category='Charging',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DoorState': SignalMeta(
        field_id=58,
        category='Vehicle State',
        value_type='enum',
        enum_name='Doors',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'Locked': SignalMeta(
        field_id=59,
        category='Safety',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'FdWindow': SignalMeta(
        field_id=60,
        category='Vehicle State',
        value_type='enum',
        enum_name='WindowState',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'FpWindow': SignalMeta(
        field_id=61,
        category='Vehicle State',
        value_type='enum',
        enum_name='WindowState',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'RdWindow': SignalMeta(
        field_id=62,
        category='Vehicle State',
        value_type='enum',
        enum_name='WindowState',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'RpWindow': SignalMeta(
        field_id=63,
        category='Vehicle State',
        value_type='enum',
        enum_name='WindowState',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'VehicleName': SignalMeta(
        field_id=64,
        category='Vehicle Configuration',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'SentryMode': SignalMeta(
        field_id=65,
        category='Vehicle State',
        value_type='enum',
        enum_name='SentryModeState',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'SpeedLimitMode': SignalMeta(
        field_id=66,
        category='Vehicle State',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'CurrentLimitMph': SignalMeta(
        field_id=67,
        category='Vehicle State',
        value_type='real',
        enum_name=None,
        unit='mph',
        device_class='speed',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'Version': SignalMeta(
        field_id=68,
        category='Vehicle Configuration',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'TpmsPressureFl': SignalMeta(
        field_id=69,
        category='Service',
        value_type='real',
        enum_name=None,
        unit='bar',
        device_class='pressure',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'TpmsPressureFr': SignalMeta(
        field_id=70,
        category='Service',
        value_type='real',
        enum_name=None,
        unit='bar',
        device_class='pressure',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'TpmsPressureRl': SignalMeta(
        field_id=71,
        category='Service',
        value_type='real',
        enum_name=None,
        unit='bar',
        device_class='pressure',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'TpmsPressureRr': SignalMeta(
        field_id=72,
        category='Service',
        value_type='real',
        enum_name=None,
        unit='bar',
        device_class='pressure',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'SemitruckTpmsPressureRe1L0': SignalMeta(
        field_id=73,
        category='Service',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=True,
        documented=True,
    ),
    'SemitruckTpmsPressureRe1L1': SignalMeta(
        field_id=74,
        category='Service',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=True,
        documented=True,
    ),
    'SemitruckTpmsPressureRe1R0': SignalMeta(
        field_id=75,
        category='Service',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=True,
        documented=True,
    ),
    'SemitruckTpmsPressureRe1R1': SignalMeta(
        field_id=76,
        category='Service',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=True,
        documented=True,
    ),
    'SemitruckTpmsPressureRe2L0': SignalMeta(
        field_id=77,
        category='Service',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=True,
        documented=True,
    ),
    'SemitruckTpmsPressureRe2L1': SignalMeta(
        field_id=78,
        category='Service',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=True,
        documented=True,
    ),
    'SemitruckTpmsPressureRe2R0': SignalMeta(
        field_id=79,
        category='Service',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=True,
        documented=True,
    ),
    'SemitruckTpmsPressureRe2R1': SignalMeta(
        field_id=80,
        category='Service',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=True,
        documented=True,
    ),
    'TpmsLastSeenPressureTimeFl': SignalMeta(
        field_id=81,
        category='Service',
        value_type='timestamp',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'TpmsLastSeenPressureTimeFr': SignalMeta(
        field_id=82,
        category='Service',
        value_type='timestamp',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'TpmsLastSeenPressureTimeRl': SignalMeta(
        field_id=83,
        category='Service',
        value_type='timestamp',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'TpmsLastSeenPressureTimeRr': SignalMeta(
        field_id=84,
        category='Service',
        value_type='timestamp',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'InsideTemp': SignalMeta(
        field_id=85,
        category='Climate',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'OutsideTemp': SignalMeta(
        field_id=86,
        category='Climate',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'SeatHeaterLeft': SignalMeta(
        field_id=87,
        category='Climate',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'SeatHeaterRight': SignalMeta(
        field_id=88,
        category='Climate',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'SeatHeaterRearLeft': SignalMeta(
        field_id=89,
        category='Climate',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'SeatHeaterRearRight': SignalMeta(
        field_id=90,
        category='Climate',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'SeatHeaterRearCenter': SignalMeta(
        field_id=91,
        category='Climate',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'AutoSeatClimateLeft': SignalMeta(
        field_id=92,
        category='Climate',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'AutoSeatClimateRight': SignalMeta(
        field_id=93,
        category='Climate',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DriverSeatBelt': SignalMeta(
        field_id=94,
        category='Safety',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'PassengerSeatBelt': SignalMeta(
        field_id=95,
        category='Safety',
        value_type='enum',
        enum_name='BuckleStatus',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DriverSeatOccupied': SignalMeta(
        field_id=96,
        category='Vehicle State',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'SemitruckPassengerSeatFoldPosition': SignalMeta(
        field_id=97,
        category='Vehicle State',
        value_type='enum',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=True,
        documented=True,
    ),
    'LateralAcceleration': SignalMeta(
        field_id=98,
        category='Driving',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'LongitudinalAcceleration': SignalMeta(
        field_id=99,
        category='Driving',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'CruiseSetSpeed': SignalMeta(
        field_id=101,
        category='Driving',
        value_type='real',
        enum_name=None,
        unit='mph',
        device_class='speed',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'LifetimeEnergyUsed': SignalMeta(
        field_id=102,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='kWh',
        device_class='energy',
        state_class='total_increasing',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'LifetimeEnergyUsedDrive': SignalMeta(
        field_id=103,
        category='Driving',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=True,
        documented=True,
    ),
    'SemitruckTractorParkBrakeStatus': SignalMeta(
        field_id=104,
        category='Vehicle State',
        value_type='enum',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=True,
        documented=True,
    ),
    'SemitruckTrailerParkBrakeStatus': SignalMeta(
        field_id=105,
        category='Vehicle State',
        value_type='enum',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=True,
        documented=True,
    ),
    'BrakePedalPos': SignalMeta(
        field_id=106,
        category='Driving',
        value_type='real',
        enum_name=None,
        unit='%',
        device_class=None,
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'RouteLastUpdated': SignalMeta(
        field_id=107,
        category='Location',
        value_type='time',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.26',
        semi_only=False,
        documented=True,
    ),
    'RouteLine': SignalMeta(
        field_id=108,
        category='Location',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.26',
        semi_only=False,
        documented=True,
    ),
    'MilesToArrival': SignalMeta(
        field_id=109,
        category='Location',
        value_type='real',
        enum_name=None,
        unit='mi',
        device_class='distance',
        state_class='measurement',
        min_firmware='2024.26',
        semi_only=False,
        documented=True,
    ),
    'MinutesToArrival': SignalMeta(
        field_id=110,
        category='Location',
        value_type='real',
        enum_name=None,
        unit='min',
        device_class='duration',
        state_class='measurement',
        min_firmware='2024.26',
        semi_only=False,
        documented=True,
    ),
    'OriginLocation': SignalMeta(
        field_id=111,
        category='Location',
        value_type='Location',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.26',
        semi_only=False,
        documented=True,
    ),
    'DestinationLocation': SignalMeta(
        field_id=112,
        category='Location',
        value_type='Location',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.26',
        semi_only=False,
        documented=True,
    ),
    'CarType': SignalMeta(
        field_id=113,
        category='Vehicle Configuration',
        value_type='enum',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'Trim': SignalMeta(
        field_id=114,
        category='Vehicle Configuration',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ExteriorColor': SignalMeta(
        field_id=115,
        category='Vehicle Configuration',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'RoofColor': SignalMeta(
        field_id=116,
        category='Vehicle Configuration',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ChargePort': SignalMeta(
        field_id=117,
        category='Charging',
        value_type='enum',
        enum_name='ChargePortValue',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ChargePortLatch': SignalMeta(
        field_id=118,
        category='Charging',
        value_type='enum',
        enum_name='ChargePortLatchValue',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'GuestModeEnabled': SignalMeta(
        field_id=123,
        category='Vehicle State',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'PinToDriveEnabled': SignalMeta(
        field_id=124,
        category='Safety',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'PairedPhoneKeyAndKeyFobQty': SignalMeta(
        field_id=125,
        category='Vehicle State',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'CruiseFollowDistance': SignalMeta(
        field_id=126,
        category='Safety',
        value_type='enum',
        enum_name='FollowDistance',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'AutomaticBlindSpotCamera': SignalMeta(
        field_id=127,
        category='Safety',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'BlindSpotCollisionWarningChime': SignalMeta(
        field_id=128,
        category='Safety',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'SpeedLimitWarning': SignalMeta(
        field_id=129,
        category='Safety',
        value_type='enum',
        enum_name='SpeedAssistLevel',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ForwardCollisionWarning': SignalMeta(
        field_id=130,
        category='Safety',
        value_type='enum',
        enum_name='ForwardCollisionSensitivity',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'LaneDepartureAvoidance': SignalMeta(
        field_id=131,
        category='Safety',
        value_type='enum',
        enum_name='LaneAssistLevel',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'EmergencyLaneDepartureAvoidance': SignalMeta(
        field_id=132,
        category='Safety',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'AutomaticEmergencyBrakingOff': SignalMeta(
        field_id=133,
        category='Safety',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'LifetimeEnergyGainedRegen': SignalMeta(
        field_id=134,
        category=None,
        value_type=None,
        enum_name=None,
        unit='kWh',
        device_class='energy',
        state_class='total_increasing',
        min_firmware=None,
        semi_only=False,
        documented=False,
    ),
    'DiStateF': SignalMeta(
        field_id=135,
        category='Powertrain',
        value_type='enum',
        enum_name='DriveInverterState',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiStateREL': SignalMeta(
        field_id=136,
        category='Powertrain',
        value_type='enum',
        enum_name='DriveInverterState',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiStateRER': SignalMeta(
        field_id=137,
        category='Powertrain',
        value_type='enum',
        enum_name='DriveInverterState',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiHeatsinkTF': SignalMeta(
        field_id=138,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiHeatsinkTREL': SignalMeta(
        field_id=139,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiHeatsinkTRER': SignalMeta(
        field_id=140,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiAxleSpeedF': SignalMeta(
        field_id=141,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiAxleSpeedREL': SignalMeta(
        field_id=142,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiAxleSpeedRER': SignalMeta(
        field_id=143,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiSlaveTorqueCmd': SignalMeta(
        field_id=144,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiTorqueActualR': SignalMeta(
        field_id=145,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiTorqueActualF': SignalMeta(
        field_id=146,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiTorqueActualREL': SignalMeta(
        field_id=147,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiTorqueActualRER': SignalMeta(
        field_id=148,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiStatorTempF': SignalMeta(
        field_id=149,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiStatorTempREL': SignalMeta(
        field_id=150,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiStatorTempRER': SignalMeta(
        field_id=151,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiVBatF': SignalMeta(
        field_id=152,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='V',
        device_class='voltage',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiVBatREL': SignalMeta(
        field_id=153,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='V',
        device_class='voltage',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiVBatRER': SignalMeta(
        field_id=154,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='V',
        device_class='voltage',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiMotorCurrentF': SignalMeta(
        field_id=155,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='A',
        device_class='current',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiMotorCurrentREL': SignalMeta(
        field_id=156,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='A',
        device_class='current',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiMotorCurrentRER': SignalMeta(
        field_id=157,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='A',
        device_class='current',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'EnergyRemaining': SignalMeta(
        field_id=158,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='kWh',
        device_class='energy_storage',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'ServiceMode': SignalMeta(
        field_id=159,
        category='Vehicle State',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'BMSState': SignalMeta(
        field_id=160,
        category='Charging',
        value_type='enum',
        enum_name='BMSStateValue',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'GuestModeMobileAccessState': SignalMeta(
        field_id=161,
        category='Vehicle State',
        value_type='enum',
        enum_name='GuestModeMobileAccess',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DestinationName': SignalMeta(
        field_id=163,
        category='Location',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.26',
        semi_only=False,
        documented=True,
    ),
    'DiInverterTR': SignalMeta(
        field_id=164,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiInverterTF': SignalMeta(
        field_id=165,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiInverterTREL': SignalMeta(
        field_id=166,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DiInverterTRER': SignalMeta(
        field_id=167,
        category='Powertrain',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware=None,
        semi_only=False,
        documented=True,
    ),
    'DetailedChargeState': SignalMeta(
        field_id=179,
        category='Charging',
        value_type='enum',
        enum_name='DetailedChargeStateValue',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware='2024.38',
        semi_only=False,
        documented=True,
    ),
    'CabinOverheatProtectionMode': SignalMeta(
        field_id=180,
        category='Climate',
        value_type='enum',
        enum_name='CabinOverheatProtectionModeState',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'CabinOverheatProtectionTemperatureLimit': SignalMeta(
        field_id=181,
        category='Climate',
        value_type='enum',
        enum_name='ClimateOverheatProtectionTempLimit',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'CenterDisplay': SignalMeta(
        field_id=182,
        category='Vehicle State',
        value_type='enum',
        enum_name='DisplayState',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'ChargePortDoorOpen': SignalMeta(
        field_id=183,
        category='Charging',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'ChargerVoltage': SignalMeta(
        field_id=184,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='V',
        device_class='voltage',
        state_class='measurement',
        min_firmware='2024.44.32',
        semi_only=False,
        documented=True,
    ),
    'ChargingCableType': SignalMeta(
        field_id=185,
        category='Charging',
        value_type='enum',
        enum_name='CableType',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'ClimateKeeperMode': SignalMeta(
        field_id=186,
        category='Climate',
        value_type='enum',
        enum_name='ClimateKeeperModeState',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'DefrostForPreconditioning': SignalMeta(
        field_id=187,
        category='Climate',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'DefrostMode': SignalMeta(
        field_id=188,
        category='Climate',
        value_type='enum',
        enum_name='DefrostModeState',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'EfficiencyPackage': SignalMeta(
        field_id=189,
        category='Vehicle Configuration',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'EstimatedHoursToChargeTermination': SignalMeta(
        field_id=190,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='h',
        device_class='duration',
        state_class='measurement',
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'EuropeVehicle': SignalMeta(
        field_id=191,
        category='Vehicle Configuration',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'ExpectedEnergyPercentAtTripArrival': SignalMeta(
        field_id=192,
        category='Charging',
        value_type='integer',
        enum_name=None,
        unit='%',
        device_class='battery',
        state_class='measurement',
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'FastChargerType': SignalMeta(
        field_id=193,
        category='Charging',
        value_type='enum',
        enum_name='FastCharger',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'HomelinkDeviceCount': SignalMeta(
        field_id=194,
        category='Vehicle State',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'HomelinkNearby': SignalMeta(
        field_id=195,
        category='Vehicle State',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'HvacACEnabled': SignalMeta(
        field_id=196,
        category='Climate',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'HvacAutoMode': SignalMeta(
        field_id=197,
        category='Climate',
        value_type='enum',
        enum_name='HvacAutoModeState',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'HvacFanSpeed': SignalMeta(
        field_id=198,
        category='Climate',
        value_type='integer',
        enum_name=None,
        unit='%',
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'HvacFanStatus': SignalMeta(
        field_id=199,
        category='Climate',
        value_type='integer',
        enum_name=None,
        unit='%',
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'HvacLeftTemperatureRequest': SignalMeta(
        field_id=200,
        category='Climate',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'HvacPower': SignalMeta(
        field_id=201,
        category='Climate',
        value_type='enum',
        enum_name='HvacPowerState',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'HvacRightTemperatureRequest': SignalMeta(
        field_id=202,
        category='Climate',
        value_type='real',
        enum_name=None,
        unit='°C',
        device_class='temperature',
        state_class='measurement',
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'HvacSteeringWheelHeatAuto': SignalMeta(
        field_id=203,
        category='Climate',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'HvacSteeringWheelHeatLevel': SignalMeta(
        field_id=204,
        category='Climate',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'OffroadLightbarPresent': SignalMeta(
        field_id=205,
        category='Vehicle Configuration',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'PowershareHoursLeft': SignalMeta(
        field_id=206,
        category='Charging',
        value_type='integer',
        enum_name=None,
        unit='h',
        device_class='duration',
        state_class='measurement',
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'PowershareInstantaneousPowerKW': SignalMeta(
        field_id=207,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='kW',
        device_class='power',
        state_class='measurement',
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'PowershareStatus': SignalMeta(
        field_id=208,
        category='Charging',
        value_type='enum',
        enum_name='PowershareState',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'PowershareStopReason': SignalMeta(
        field_id=209,
        category='Charging',
        value_type='enum',
        enum_name='PowershareStopReasonStatus',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'PowershareType': SignalMeta(
        field_id=210,
        category='Charging',
        value_type='enum',
        enum_name='PowershareTypeStatus',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'RearDisplayHvacEnabled': SignalMeta(
        field_id=211,
        category='Climate',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'RearSeatHeaters': SignalMeta(
        field_id=212,
        category='Vehicle Configuration',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'RemoteStartEnabled': SignalMeta(
        field_id=213,
        category='Vehicle Configuration',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'RightHandDrive': SignalMeta(
        field_id=214,
        category='Vehicle Configuration',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'RouteTrafficMinutesDelay': SignalMeta(
        field_id=215,
        category='Driving',
        value_type='real',
        enum_name=None,
        unit='min',
        device_class='duration',
        state_class='measurement',
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'SoftwareUpdateDownloadPercentComplete': SignalMeta(
        field_id=216,
        category='Vehicle State',
        value_type='integer',
        enum_name=None,
        unit='%',
        device_class=None,
        state_class='measurement',
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'SoftwareUpdateExpectedDurationMinutes': SignalMeta(
        field_id=217,
        category='Vehicle State',
        value_type='integer',
        enum_name=None,
        unit='min',
        device_class='duration',
        state_class='measurement',
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'SoftwareUpdateInstallationPercentComplete': SignalMeta(
        field_id=218,
        category='Vehicle State',
        value_type='integer',
        enum_name=None,
        unit='%',
        device_class=None,
        state_class='measurement',
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'SoftwareUpdateScheduledStartTime': SignalMeta(
        field_id=219,
        category='Vehicle State',
        value_type='timestamp',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'SoftwareUpdateVersion': SignalMeta(
        field_id=220,
        category='Vehicle State',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'TonneauOpenPercent': SignalMeta(
        field_id=221,
        category='Vehicle State',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'TonneauPosition': SignalMeta(
        field_id=222,
        category='Vehicle State',
        value_type='enum',
        enum_name='TonneauPositionState',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'TonneauTentMode': SignalMeta(
        field_id=223,
        category='Vehicle State',
        value_type='enum',
        enum_name='TonneauTentModeState',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'TpmsHardWarnings': SignalMeta(
        field_id=224,
        category='Service',
        value_type='enum',
        enum_name='TireLocation',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'TpmsSoftWarnings': SignalMeta(
        field_id=225,
        category='Service',
        value_type='enum',
        enum_name='TireLocation',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'ValetModeEnabled': SignalMeta(
        field_id=226,
        category='Vehicle State',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'WheelType': SignalMeta(
        field_id=227,
        category='Vehicle Configuration',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'WiperHeatEnabled': SignalMeta(
        field_id=228,
        category='Climate',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.25',
        semi_only=False,
        documented=True,
    ),
    'LocatedAtHome': SignalMeta(
        field_id=229,
        category='Location',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.32',
        semi_only=False,
        documented=True,
    ),
    'LocatedAtWork': SignalMeta(
        field_id=230,
        category='Location',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.32',
        semi_only=False,
        documented=True,
    ),
    'LocatedAtFavorite': SignalMeta(
        field_id=231,
        category='Location',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.32',
        semi_only=False,
        documented=True,
    ),
    'SettingDistanceUnit': SignalMeta(
        field_id=232,
        category='User Preference',
        value_type='enum',
        enum_name='DistanceUnit',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.32',
        semi_only=False,
        documented=True,
    ),
    'SettingTemperatureUnit': SignalMeta(
        field_id=233,
        category='User Preference',
        value_type='enum',
        enum_name='TemperatureUnit',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.32',
        semi_only=False,
        documented=True,
    ),
    'Setting24HourTime': SignalMeta(
        field_id=234,
        category='User Preference',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.32',
        semi_only=False,
        documented=True,
    ),
    'SettingTirePressureUnit': SignalMeta(
        field_id=235,
        category='User Preference',
        value_type='enum',
        enum_name='PressureUnit',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.32',
        semi_only=False,
        documented=True,
    ),
    'SettingChargeUnit': SignalMeta(
        field_id=236,
        category='User Preference',
        value_type='enum',
        enum_name='ChargeUnitPreference',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.32',
        semi_only=False,
        documented=True,
    ),
    'ClimateSeatCoolingFrontLeft': SignalMeta(
        field_id=237,
        category='Climate',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.32',
        semi_only=False,
        documented=True,
    ),
    'ClimateSeatCoolingFrontRight': SignalMeta(
        field_id=238,
        category='Climate',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2024.44.32',
        semi_only=False,
        documented=True,
    ),
    'LightsHazardsActive': SignalMeta(
        field_id=239,
        category='Vehicle State',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'LightsTurnSignal': SignalMeta(
        field_id=240,
        category='Vehicle State',
        value_type='enum',
        enum_name='TurnSignalState',
        unit=None,
        device_class='enum',
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'LightsHighBeams': SignalMeta(
        field_id=241,
        category='Vehicle State',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'MediaPlaybackStatus': SignalMeta(
        field_id=242,
        category='Media',
        value_type='enum',
        enum_name='MediaStatus',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'MediaPlaybackSource': SignalMeta(
        field_id=243,
        category='Media',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'MediaAudioVolume': SignalMeta(
        field_id=244,
        category='Media',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'MediaNowPlayingDuration': SignalMeta(
        field_id=245,
        category='Media',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'MediaNowPlayingElapsed': SignalMeta(
        field_id=246,
        category='Media',
        value_type='integer',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'MediaNowPlayingArtist': SignalMeta(
        field_id=247,
        category='Media',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'MediaNowPlayingTitle': SignalMeta(
        field_id=248,
        category='Media',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'MediaNowPlayingAlbum': SignalMeta(
        field_id=249,
        category='Media',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'MediaNowPlayingStation': SignalMeta(
        field_id=250,
        category='Media',
        value_type='string',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'MediaAudioVolumeIncrement': SignalMeta(
        field_id=251,
        category='Media',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'MediaAudioVolumeMax': SignalMeta(
        field_id=252,
        category='Media',
        value_type='real',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'SunroofInstalled': SignalMeta(
        field_id=253,
        category='Vehicle Configuration',
        value_type='enum',
        enum_name='SunroofInstalledState',
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'SeatVentEnabled': SignalMeta(
        field_id=254,
        category='Climate',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'RearDefrostEnabled': SignalMeta(
        field_id=255,
        category='Climate',
        value_type='boolean',
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'ChargeRateMilePerHour': SignalMeta(
        field_id=256,
        category='Charging',
        value_type='real',
        enum_name=None,
        unit='mph',
        device_class='speed',
        state_class='measurement',
        min_firmware='2025.2.6',
        semi_only=False,
        documented=True,
    ),
    'MilesSinceReset': SignalMeta(
        field_id=258,
        category='Safety',
        value_type='real',
        enum_name=None,
        unit='mi',
        device_class='distance',
        state_class='total_increasing',
        min_firmware='2025.44.25.5',
        semi_only=False,
        documented=True,
    ),
    'SelfDrivingMilesSinceReset': SignalMeta(
        field_id=259,
        category='Safety',
        value_type='real',
        enum_name=None,
        unit='mi',
        device_class='distance',
        state_class='total_increasing',
        min_firmware='2025.44.25.5',
        semi_only=False,
        documented=True,
    ),
    'GpsAccuracyMeters': SignalMeta(
        field_id=260,
        category=None,
        value_type=None,
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2026.32',
        semi_only=False,
        documented=False,
    ),
    'LifetimeEnergyChargedKwh': SignalMeta(
        field_id=261,
        category=None,
        value_type=None,
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2026.32',
        semi_only=False,
        documented=False,
    ),
    'BrickSocMinPercent': SignalMeta(
        field_id=262,
        category=None,
        value_type=None,
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2026.32',
        semi_only=False,
        documented=False,
    ),
    'NominalFullPackEnergyKwh': SignalMeta(
        field_id=263,
        category=None,
        value_type=None,
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2026.32',
        semi_only=False,
        documented=False,
    ),
    'GradeEstimatePercent': SignalMeta(
        field_id=264,
        category=None,
        value_type=None,
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2026.32',
        semi_only=False,
        documented=False,
    ),
    'MaxSpeedToReachDestinationMph': SignalMeta(
        field_id=265,
        category=None,
        value_type=None,
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2026.32',
        semi_only=False,
        documented=False,
    ),
    'SoftwareUpdateAvailable': SignalMeta(
        field_id=266,
        category=None,
        value_type=None,
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2026.32',
        semi_only=False,
        documented=False,
    ),
    'SoftwareUpdateInProgress': SignalMeta(
        field_id=267,
        category=None,
        value_type=None,
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2026.32',
        semi_only=False,
        documented=False,
    ),
    'RemoteStartActive': SignalMeta(
        field_id=268,
        category=None,
        value_type=None,
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2026.32',
        semi_only=False,
        documented=False,
    ),
    'SemiCruiseSpeedLimitMph': SignalMeta(
        field_id=269,
        category=None,
        value_type=None,
        enum_name=None,
        unit=None,
        device_class=None,
        state_class=None,
        min_firmware='2026.32',
        semi_only=True,
        documented=False,
    ),
}
